### PR TITLE
libgit2-sys: update libgit2 to fix build with libressl

### LINKED ISSUE #212: `libgit2-sys` Version `0.6.11` fails to build with LibreSSL
This seems to be caused by https://github.com/libgit2/libgit2/issues/4220 - upstream is preparing a new release: https://github.com/libgit2/libgit2/issues/4227. Version `0.6.10` is known to work. I'm not sure we can do anything about it *here*, but I think it should be at least pointed out.

### PR DESCRIPTION
**Pull request by Keruspe**
Fixes #212

### CODE REVIEW

**Comment by Keruspe** [comment]
Second commit is there for a build failure with MSVC on appveyor, with a conflict between u32 and i32 for those types

**Comment by alexcrichton** [comment]
Thanks! I personally prefer to keep the `raw` types out of the public API if possible, could the bitflags stay with a `u32` behind them?

**Comment by Keruspe** [comment]
Yes, but then we hit this failure: https://ci.appveyor.com/project/alexcrichton/git2-rs/build/1.0.903

**Comment by alexcrichton** [comment]
That just requires an extra `as u32` though?

**Comment by Keruspe** [comment]
Yeah, right, thoguht of it backwards, fixing

**Comment by Keruspe** [comment]
Note that this is needed to be able to build nightly (and probably the new beta) of rustc

**Comment by alexcrichton** [comment]
Looks good to me, thanks!

**Pull request merged**
