### PR TITLE
Update libgit2 to c8fe6c097

### PR DESCRIPTION
**Pull request by carlosmn**
This is the libgit2 version that'll be the first rc. It doesn't look like you generally follow releases, but I've been going around a few bindings to update them, so here it is.

I don't know how you handle version numbers, so I haven't touched them here.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Oh awesome, thanks so much! I'll handle the version and do a release soon as well.

Looks like travis/appveyor didn't get triggered first time around, so I'm gonna close and reopen in hopes of pinging them.

**Comment by alexcrichton** [comment]
Looks like `git_diff_options` and `git_merge_options` also changed between now and the current submodule?

**Comment by carlosmn** [comment]
Looks like I forgot to update a copule "tree flags" -> flags and actually chopped off the wrong part of the payload name. It should be fine now.

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
