### PR TITLE
Add index flags and index extended flags

### PR DESCRIPTION
**Pull request by joshtriplett**
Needed for the `flags` and `extended_flags` fields of IndexEntry

### CODE REVIEW

**Comment by alexcrichton** [comment]
Hm I wonder if in light of https://github.com/alexcrichton/git2-rs/issues/138 if the entire `IndexEntry` API should get overhauled? Perhaps a bunch of boolean accessors/setters instead of a flag-based API, along with validation and whitelists to ensure we don't allow the same sort of memory corruption. What do you think?

Eventually I'd kinda like to move toward a world where we don't use `bitflags!` in git2-rs at all...

**Comment by joshtriplett** [comment]
I'm not sure you'll be able to do without `bitflags!` entirely, given that some APIs accept flags directly. And I don't know if it makes sense for every data structure that contains a flags field to expand it out into accessors, if there's more than one structure containing the same set of flags (that'd take a bit of an audit).  But I do agree that `IndexEntry` needs an overhaul, and it might make sense to automatically handle things like "valid" and "extended" (the latter being set if any of `flags_extended` are set).  So in the particular case of `IndexEntry`, I think accessors would make sense, though I'd still suggest having a way to get and set the entire `flags_extended` field at once, too.

**Comment by alexcrichton** [comment]
Hm could you expand a bit on why you think we'd still want the ability to set `flags_extended` all at once? One major downside I've seen with flags is that they aren't documented well as it's difficult to see what the set of flags are. They're also not necessarily as idiomatic in Rust as they are in C, so they typically feel a little awkward to use.

I'd at least prefer when reading code to see the Rust-style accessors and setters as it'd fit in well (in theory at least).

**Comment by joshtriplett** [comment]
@alexcrichton I had been thinking about the case of repeatedly using the same `flags_extended` for different index entries, but it occurs to me that cloning the whole IndexEntry and changing the name/oid would probably work better for that.  So nevermind; putting all the accessors directly on the IndexEntry seems fine.

**Comment by alexcrichton** [comment]
Ok, I may try to get around to just a wholly redesigned `IndexEntry` tonight and see what happens

**Comment by alexcrichton** [comment]
Ok I think I'm gonna go ahead and merge this for now, fixup the memory safety issues, and we can perhaps push for a different design later. Unfortunately I'm running short on time nowadays :(

**Comment by alexcrichton** [comment]
Thanks though!

**Pull request merged**
