### PR TITLE
Please provide binding for git_config_parse_bool

### PR DESCRIPTION
**Pull request by joshtriplett**
To make it easier to handle git config values that can take either a bool or a string, I'd like to have a binding for git_config_parse_bool.  That would make it easier to get a value as a string, check if it's a valid bool, and handle it as a string otherwise.

I would suggest the type `fn config_parse_bool<S: IntoCString>(s: S) -> Result<bool, Error>`

### CODE REVIEW

**Comment by joshtriplett** [comment]
Attached a pull request adding `config_parse_bool`, along with `config_parse_i32`, `config_parse_i64`, and tests.

**Comment by alexcrichton** [comment]
Thanks! I wonder if these may perhaps be better placed as `Config::parse_bool` or something like that?

**Comment by joshtriplett** [comment]
As static methods that don't take self or return Self?  I can do that if you prefer.  They don't have anything to do with creating or manipulating a Config, but this change wouldn't impact usability at all, so I don't care what color the bikeshed is painted. :)

Let me know your preference and I'll make the change if needed.

**Comment by joshtriplett** [comment]
I've pushed a version of this as static functions to [my config_parse_static](https://github.com/joshtriplett/git2-rs/tree/config_parse_static) branch; let me know and I can force-push that to this pull request instead.

**Comment by alexcrichton** [comment]
Ah yeah that's what I was thinking, just generally one less thing to import hopefully if you're already working with `Config` :)

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
