### PR TITLE
Add script to automatically generate tests for pub structs

### PR DESCRIPTION
**Pull request by nbigaouette**
This PR adds a bash script that will get all structs marked `pub` and, if their module has not been `pub` exported, will generate a simple test that try to `use` them.

Reported in #260, a struct was found to not have been re-exported at the lib level. I did remember that I found the same issue with another struct, but couldn't remember which one. Since there is many, I decided to script this to detect any error. Found 3 other structs (`ParentIds`, `StashCbData` and `TestTreeIter`). I'm not sure one of those was the one I had issue with initially, but they should still be fixed.

The PR will add the tests and their fix.

I'll push the commits one after the other to trigger the CI at every step.

### CODE REVIEW

**Comment by nbigaouette** [comment]
Turns out, `TestTreeIter` is a test struct... urg. I've changed the script to start match at beginning of line.

I've force pushed to change this:

* 4c3de54 -> e6ace15
* 03d0073 -> f998bc7

**Comment by nbigaouette** [comment]
Unfortunately, `StashCbData` is not documented, which will prevent the crate to build... :(

**Comment by nbigaouette** [comment]
I've added (in 8cdfc78) the execution of the script to Travis config, making sure that the tests are always up to date.

I'm not sure about AppVeyor though (bash on windows? pipes? might be problematic...) but Travis is probably sufficient.

**Comment by alexcrichton** [comment]
Thanks! My shell-fu is pretty awful, but I wonder if this could perhaps be a test that's generated from a build script?

**Comment by nbigaouette** [comment]
I wish I was as fluent in rust as I'm in shell ;)

It would definitely be better in rust though. I'll see what I can do!

**Comment by nbigaouette** [comment]
By the way, what should be done about the missing docstring? Is that struct ok being public? What is it's meaning?

**Comment by alexcrichton** [comment]
It's ok to either fill in the docs or tag it with `#[allow(missing_docs)]` for now

**Comment by nbigaouette** [comment]
I'm working on a `build.rs` version... should be coming soon ;)

**Comment by alexcrichton** [comment]
Thanks! A few comments on the organization here (but otherwise looks great)

* Could this generate code into the build directory rather than the source directory? You should be able to include that via `include!` in the test itself.
* Could the build script be moved to a separate project? (something like a `git2-test` folder). That way we won't have to worry about this running by accident and/or failing when git2 is used as a crate (not with tests)

**Comment by alexcrichton** [comment]
I'm going to close this due to inactivity for now, but it can always be resubmitted!

**Pull request closed without merging**
