### PR TITLE
Update libgit2 for libressl compatibility

### PR DESCRIPTION
**Pull request by Keruspe**

### CODE REVIEW

**Comment by Keruspe** [comment]
This fixes #178

**Comment by Keruspe** [comment]
What do you mean? It's already separated commits, or maybe I misunderstood something?
Do you want me to get rid of the two last commits and keep only the first one?

**Comment by alexcrichton** [comment]
Yeah let's just drop those commits from this PR

**Comment by Keruspe** [comment]
Done

**Pull request merged**
