### PR TITLE
Add Debug implementation for bunch of objects

### PR DESCRIPTION
**Pull request by uzytkownik**
This is useful for unwrap from results and other things.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Could this perhaps make use of the debug builders on `Formatter` to have formatted output as well?

**Comment by uzytkownik** [comment]
You mean something like that? If not I'm not sure I understend.

**Comment by alexcrichton** [comment]
Oh sorry, what I meant was something like:

```rust
f.debug_struct("Foo")
    .field("id", &self.id())
    .finish()
```

**Comment by uzytkownik** [comment]
Done

**Comment by alexcrichton** [comment]
Thanks! Looks like CI is failing though?

**Comment by uzytkownik** [comment]
Sorry - I haven't checked the tests which were broken by relaxation (warning promoted to error). Should be fixed now.

**Comment by alexcrichton** [comment]
👍

**Pull request merged**
