### PR TITLE
Added git_hash_* declarations

### PR DESCRIPTION
**Pull request by Cyclic3**
Except for git_hash_vec, which requires git_buf_vec, which is not defined or used by the rest of the crate

#220

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Did you want to add high level bindings to this as well?

**Comment by Cyclic3** [comment]
How's that?

**Comment by alexcrichton** [comment]
Oh so I just realized, this isn't actually part of the public API of libgit2? The CI is failing because the function is undefined, and that's because this function is only defined in an internal header. I don't think it's expected that downstream consumers use this function?

**Comment by Cyclic3** [comment]
The low level functions do not work (the ones that use git_hash_ctx), but git_wrap_buf does. I have compiled and used this, and I hate to be the guy who says `this works for me`, but I have seen no problem with it.

**Comment by alexcrichton** [comment]
Unfortunately this crate only exposes the public API of libgit2, so if we want to expose this then you'd want to first convince libgit2 maintainers to expose it upstream.

**Comment by Cyclic3** [comment]
Ok, I will talk to them. I'll close this issue for now, and reopen it if the libgit2 devs accept it.

BTW, why can I interface with it on my machine and Travis can't?

**Pull request closed without merging**
